- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Get Auth token
      uri:
        url: https://192.168.2.124/mgmt/shared/authn/login
        method: POST
        body:
          username: admin
          password: admin
          loginProviderName: "tmos"
        body_format: json
        return_content: yes
        status_code: 200
        validate_certs: false
        register: auth_token

    - name: Display auth_token
      debug:
        msg: "{{ stdout.json.token.token | from_json }}"

    - name: Copy auth_token to a variable
      set_fact:
        auth_token: "{{ auth_token }}"

    - name: Send DO blob to bigip
      uri:
        url: https://192.168.2.124/mgmt/shared/declarative-onboarding
        headers:
          X-F5-Auth-Token: "{{ auth_token }}"
        method: POST
        src: "./do_bigip.json"
        body_format: json
        return_value: true
        validate_certs: false
